"use client";

import './globals.css'
import { usePathname } from "next/navigation";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const currentRoute = usePathname();

  const changeColor = (route: any) => {
    let color = '';

    if(route === '/assistenciais') {
      color = "bg-[#c62828]"
    }
    if(route === '/administrativos') {
      color = "bg-[#558b2f]"
    }
    if(route === '/ensino') {
      color = "bg-[#283593]"
    }
    if(route === '/formularios') {
      color = "bg-[#00695c]"
    }
    if(route === '/relatorios') {
      color = "bg-[#37474f]"
    }
    if(route === '/emails-institucionais') {
      color = "bg-[#0277bd]"
    }
    if(route === '/portais') {
      color = "bg-[#4527a0]"
    }
    if(route === '/treino-homologacao') {
      color = "bg-[#f9a825]"
    }
    if(route === '/restritos') {
      color = "bg-[#263238]"
    }
    if(route === '/manuais') {
      color = "bg-[#263238]"
    }
    if(route === '/ajuda') {
      color = "bg-[#263238]"
    }

    return color;
  }

  return (
    <html lang="en">
      <body className={`${inter.className} ${currentRoute ? changeColor(currentRoute) : 'bg-[#263238]'}`}>{children}</body>
    </html>
  )
}
